### ISSUE TITLE
example运行错误，麻烦能看一下吗？

### ISSUE THREAD

**Issue by woordee** [TaleAi/flutter_rongcloud_im#1]
`E/RongLog-Push[PushConfig]( 3391): appid or appkey can't be empty when enable MI push !
E/RongLog-Push[PushConfig]( 3391): appid or appkey can't be empty when enable MEIZU push !`
这个推送要在哪配置或是关闭掉？

`E/RongLog ( 3391): [ TypingMessageManager ] getTypingStatus rc_typing_status not configure in rc_configuration.xml
W/System.err( 3391): android.content.res.Resources$NotFoundException: Resource ID #0x0
W/System.err( 3391):    at android.content.res.Resources.getValue(Resources.java:1266)
W/System.err( 3391):    at android.content.res.Resources.getBoolean(Resources.java:994)
W/System.err( 3391):    at io.rong.imlib.typingmessage.TypingMessageManager.init(TypingMessageManager.java:77)
W/System.err( 3391):    at io.rong.imlib.RongIMClient.initSDK(RongIMClient.java:555)
W/System.err( 3391):    at io.rong.imlib.RongIMClient.init(RongIMClient.java:626)
W/System.err( 3391):    at io.rong.imlib.RongIMClient.init(RongIMClient.java:612)
W/System.err( 3391):    at com.ninefrost.flutterrongcloudim.RongIMLib.init(RongIMLib.java:206)
W/System.err( 3391):    at com.ninefrost.flutterrongcloudim.FlutterRongcloudImPlugin.onMethodCall(FlutterRongcloudImPlugin.java:33)
W/System.err( 3391):    at io.flutter.plugin.common.MethodChannel$IncomingMethodCallHandler.onMessage(MethodChannel.java:201)
W/System.err( 3391):    at io.flutter.embedding.engine.dart.DartMessenger.handleMessageFromDart(DartMessenger.java:88)
W/System.err( 3391):    at io.flutter.embedding.engine.FlutterJNI.handlePlatformMessage(FlutterJNI.java:219)
W/System.err( 3391):    at android.os.MessageQueue.nativePollOnce(Native Method)
W/System.err( 3391):    at android.os.MessageQueue.next(MessageQueue.java:143)
W/System.err( 3391):    at android.os.Looper.loop(Looper.java:122)
W/System.err( 3391):    at android.app.ActivityThread.main(ActivityThread.java:5254)
W/System.err( 3391):    at java.lang.reflect.Method.invoke(Native Method)
W/System.err( 3391):    at java.lang.reflect.Method.invoke(Method.java:372)
W/System.err( 3391):    at com.android.internal.os.ZygoteInit$MethodAndArgsCaller.run(ZygoteInit.java:903)
W/System.err( 3391):    at com.android.internal.os.ZygoteInit.main(ZygoteInit.java:698)
W/ResourceType( 3391): Invalid package identifier when getting bag for resource number 0x00000000`
这个错误好像是资源没找到？

**Comment by okchenyi** [comment]
兄弟运行起来了吗
